services:
  api:
    build: .
    ports:
      - "5000:5000"  # Mapeia a porta 5000 do container para a m치quina host
    volumes:
      - .:/app       # Monta o diret칩rio atual como volume no container
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_ENV=development  # Define a vari치vel de ambiente para o modo de desenvolvimento

  test:
    build: .
    volumes:
      - .:/app       # Monta o diret칩rio atual como volume no container
    command: python -m unittest discover
