version: '3.9'
services:
  app:
    build: .
    ports:
      - "1313:1313"
    environment:
      - JWT_SECRET_KEY=your_secret_key
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
