# Arquivo: .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      - name: Run unit tests
        run: |
          docker run my-app:latest python -m unittest discover -s tests

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-app:latest <dockerhub_username>/my-app:latest
          docker push <dockerhub_username>/my-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            docker pull <dockerhub_username>/my-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 1313:1313 --name my-app <dockerhub_username>/my-app:latest
