name: CI - Run Tests

on:
  push:
    branches:
      - dev 
  pull_request:
    branches:
      - dev 

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      - name: Run Unit Tests
        run: |
          docker run my-app:latest python -m unittest discover -s tests
